"""empty message

Revision ID: 1fc8af7808b9
Revises: 223fa233e64b
Create Date: 2019-12-30 13:34:07.951339

"""

# revision identifiers, used by Alembic.
revision = '1fc8af7808b9'
down_revision = '223fa233e64b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('kpis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('received', sa.DateTime(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('value', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('kpis')
    # ### end Alembic commands ###
